name: Local Auto Deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    # Only run on runners with the 'deploy' label
    if: contains(github.event.head_commit.message, '') # Run on every push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build and Restart Services
        run: |
          # Propagate existing environment variables to the checked-out directory
          echo "AIRFLOW_UID=${AIRFLOW_UID}" >> .env
          echo "AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}" >> .env
          echo "RUNNER_TOKEN=${TOKEN}" >> .env
          
          # Use the mounted host docker to redeploy
          docker compose down
          docker compose up -d --build
